line-length = 100
target-version = "py311"

[lint]
select = [
  "E","F","W","I","N","B","UP","S","C4","SIM","PL","RUF"
]
ignore = [
  "S101" # allow assert in tests
]

# Exclude generated/migration code from lint noise
exclude = [
  "alembic/*",
]

[lint.isort]
known-first-party = ["ddms"]
